# SPDX-FileCopyrightText: 2024 PNED G.I.E.
#
# SPDX-License-Identifier: Apache-2.0
version: "3"

services:
  frontend:
    build:
      context: .
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_CKAN_URL=https://ckan-test.healthdata.nl
      - NEXT_PUBLIC_DAAM_URL=http://localhost:8080
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret
      - KEYCLOAK_CLIENT_ID=ckan
      - KEYCLOAK_ISSUER_URL=https://keycloak-test.healthdata.nl/realms/ckan
      - END_SESSION_URL=https://keycloak-test.healthdata.nl/realms/ckan/protocol/openid-connect/logout
      - REFRESH_TOKEN_URL=https://keycloak-test.healthdata.nl/realms/ckan/protocol/openid-connect/token
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-qO",
          "-",
          "http://localhost:3000/api/health",
          "||",
          "exit",
          "1",
        ]
    ports:
      - "3000:3000"
