# SPDX-FileCopyrightText: 2024 PNED G.I.E.
#
# SPDX-License-Identifier: Apache-2.0

GET https://ckan-test.healthdata.nl/api/3/action/package_search?facet.field=["organization","theme","conforms_to","has_version","access_rights","language","publisher_name","res_format"]&rows=0

###
GET https://ckan-test.healthdata.nl/api/3/action/package_search?rows=0

###
GET https://ckan-test.healthdata.nl/api/3/action/tag_list